version: '3.4'
services:
  postgres:
    image: postgres:11.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: your-secret-password   #change
      POSTGRES_DB: project-db   #change
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    ports:
      - 3645:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
  migrate:
    image: migrate/migrate
    volumes:
      - ./backend/database/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://root:your-secret-password@postgres:5432/project-db?sslmode=disable", "up"]
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "nc", "-vs", "postgres", "5432"]
      interval: 1s
      timeout: 10s
      retries: 10
  api:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports: 
      - 8080:5000
    depends_on:
      - postgres
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30

volumes:
  postgres_data: